{
    'name': 'website_bensizwe',
    'version': '1.0',
    'summary': 'Custom website module for Bensizwe',
    'description': 'This module provides custom website functionalities for Bensizwe.',
    'author': 'Your Name',
    'website': 'http://www.bensizwe.com',
    'category': 'Website',
    'depends': ['website', 'website_hr_recruitment','hr'],
    "data": [
        "security/ir.model.access.csv",
        "views/hr_applicant_views.xml",
        "views/snippets/options.xml",
        "views/snippets/s_rows_jobs_out_.xml",
        "views/snippets/s_rows_jobs.xml",
        "views/website_training_template.xml",
        "views/website_training_views.xml",
        "views/website_user_views.xml",
        "views/website_training_validation_template.xml",
        "views/candidat_auth_templates.xml",
        "views/candidat_mon_espace_template.xml",
        "views/hr_job_form_inherit_extra_fields.xml",
        "views/website_job_detail_template.xml",
        "views/forms/website_form_formation.xml",
        "views/forms/ajout_experience_education_langage_templates.xml",
        "views/report_cv_pdf_template.xml",
        "views/snippets/snippet3collones_dynamic.xml"
    ],
    'assets': {
        'web.assets_frontend': [
            'website_bensizwe/static/src/scss/*.scss',
            'website_bensizwe/static/src/js/*.js',
            'website_bensizwe/static/src/img/icons/*.svg',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}